"""empty message

Revision ID: 23776acf632e
Revises: None
Create Date: 2013-11-15 21:46:08.783199

"""

# revision identifiers, used by Alembic.
revision = '23776acf632e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces_user', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('workspaces_user', sa.Column('last_name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces_user', 'last_name')
    op.drop_column('workspaces_user', 'first_name')
    ### end Alembic commands ###
