"""Add classes.

Revision ID: 56f1072c3f46
Revises: 23776acf632e
Create Date: 2013-11-15 23:56:23.392489

"""

# revision identifiers, used by Alembic.
revision = '56f1072c3f46'
down_revision = '23776acf632e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['workspaces_user.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('departments_classes',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.alter_column(u'class', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column(u'class', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'class', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'class', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_table('departments_classes')
    op.drop_table('schedules')
    op.drop_table('department')
    ### end Alembic commands ###
