"""empty message

Revision ID: 9a05f246f6c
Revises: 56f1072c3f46
Create Date: 2013-11-16 00:20:17.238829

"""

# revision identifiers, used by Alembic.
revision = '9a05f246f6c'
down_revision = '56f1072c3f46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('class', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('department', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('department', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('role', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('role', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('workspaces_user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('workspaces_user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces_user', 'updated_at')
    op.drop_column('workspaces_user', 'created_at')
    op.drop_column('role', 'updated_at')
    op.drop_column('role', 'created_at')
    op.drop_column('department', 'updated_at')
    op.drop_column('department', 'created_at')
    op.drop_column('class', 'updated_at')
    op.drop_column('class', 'created_at')
    ### end Alembic commands ###
